# restart single container
# docker-compose up -d --no-deps --build luz-online-web
version: '3.7'
services:
  database:
    build:
      context: '.\database'
    environment:
      POSTGRES_PASSWORD: 'postgres'
    # volumes:
    #  - ./log:/opt/jboss/wildfly/standalone/log
    ports:
      - 6543:5432
  app:
    build:
      context: '.'
    ports:
      - 9090:8080
  

  

